### PR TITLE
Fix broken CI builds on Zephyr 3.2

### PR DESCRIPTION
**Pull request by DerDreschner**
There are several changes in the Zephyr 3.2 branch that break several tests as well as Non-Advantage 360 builds. To ensure a high software quality and ensure being as compatible as possible to upstream, this pull request tries to fix all CI pipelines.

Tests: Commit a981282 broke the backlight tests due to changed default values. The necessary upstream default values are now used for the tests. I also considered changing the tests itself, but I value a high upstream compatibility over a "perfect fitting" repository for the Advantage 360.

Non-Advantage 360 builds: Commit 10b605e broke compatibility with several build configurations that don't use `CONFIG_ZMK_SPLIT_BLE`, `CONFIG_ZMK_RGB_UNDERGLOW` and `CONFIG_ZMK_BACKLIGHT`. I'm not sure if these code changes wouldn't fit better in their respective file inside the `behaviour` folder. But as first step I were happy with working builds using preprocessor conditions. What's your opinion on that?

For working builds with battery reporting, I needed to cherry-pick 881da25 as well. I guess this change would find their way into the branch in the near future anyway.

### CODE REVIEW

**Comment by DerDreschner** [comment]
Ahh, I recognized I had to cherry-pick that commit due to the change in 2797cc9. Do you have any experience if enabling deep sleep as proposed here https://github.com/zmkfirmware/zmk/issues/1273#issue-1217339082 is enough? What are the drawbacks that you decided to remove BT_BAS completely?

And would you be able to use the `ZMK_BATTERY_REPORTING` setting instead of remove BT_BAS? I'm a Linux user and would really like to get the current battery status without maintaining my own zmk repo in the future.

**Comment by DerDreschner** [comment]
Reverted the cherry-pick to keep the changes in this PR non-breaking. Please keep in mind that the `nice_nano_v2 kyria_left -DCONFIG_ZMK_DISPLAY=y` build is supposed to fail as there are additional code lines in `app/src/display/widgets` that rely on BT_BAS and being build in that configuration.

**Comment by ReFil** [comment]
Really sorry i missed this, I didn't get an email. Thank you for the PR, i'll look over it now

**Comment by ReFil** [comment]
> Ahh, I recognized I had to cherry-pick that commit due to the change in [2797cc9](https://github.com/ReFil/zmk/commit/2797cc918ee189979b2dca85c6f13faeeb6325bf). Do you have any experience if enabling deep sleep as proposed here [zmkfirmware#1273 (comment)](https://github.com/zmkfirmware/zmk/issues/1273#issue-1217339082) is enough? What are the drawbacks that you decided to remove BT_BAS completely?
> 
> And would you be able to use the `ZMK_BATTERY_REPORTING` setting instead of remove BT_BAS? I'm a Linux user and would really like to get the current battery status without maintaining my own zmk repo in the future.

Yes i'll be going to using the merged configuration option, disabling bas was a stopgap measure.
Enabling deep sleep for everyone runs the risk of causing split connection issues, disabling the battery reporting was a simpler option

**Comment by ReFil** [comment]
A dedicated bluetooth service to update the lights on the peripheral side is more reliable than the behaviour invocation based technique, and was vital for implementing te layer and hid indicators on the peripheral side

**Comment by ReFil** [comment]
This looks good, i need to test pulling in the latest upstream then i will merge this in. Thank you very much for your work

**Pull request merged**
