### PR TITLE
Option to turn off the BLE profile indicator during inactivity

### PR DESCRIPTION
**Pull request by cvcore**
Reason for this PR is that currently the BLE profile indicator on the left half will stay on all the time and cause a significant imbalance in the battery usage between left and right part.

Since a normal indicator LED will need up to 20mA of current, I think it's a good idea to only turn it on when needed. The new behavior will trigger it to show the color for current profile when:
- Bluetooth Connection is established for current profile
- The `Mod` key is pressed on the keyboard

for around 5 seconds before turning it off again.

But when the keyboard is powered with the USBC cable, this behavior will be disabled automatically.

### CODE REVIEW

**Comment by ReFil** [comment]
These LEDs dont draw that much current at all, but i can see why this would be useful, once the beta changes are pulled in i'll merge this

**Comment by ReFil** [comment]
There's just been a major update to the beta branch with the goal of improving bluetooth reliability between splits, would you be able to rebase your changes onto the current branch?

**Comment by cvcore** [comment]
> There's just been a major update to the beta branch with the goal of improving bluetooth reliability between splits, would you be able to rebase your changes onto the current branch?

Sure, I will try that during this weekend. Have you noticed major improvements from your side after flashing the hardware with the latest build in the z3.2 beta branch @ReFil ?

**Comment by cvcore** [comment]
So I did some testing during the merge and there exists serious regressions from the latest beta branch https://github.com/ReFil/zmk/commit/2f7db1adef5f4b01602379758ea48d940c6ab305 that the right part again refuses to connect to the left after power cycle :( 

Have you tested the latest version with your hardware and did you see the same issue? @ReFil 

**To reproduce:**

(Please note the steps below is done first without applying any patch)

1. Check out to the git version mentioned above
2. Build firmware from that version
3. Do a clean settings reset and then flash the firmware for both left and right split.
4. Power on the left half, wait 1 sec, power on the right half.

**Observation:**

For the very first time after the fresh flashing, the right half is able to connect to the left half without any issue. But it will stop working from the second time on:

https://github.com/ReFil/zmk/assets/4695324/11c844dc-6e2f-456f-b1ff-9ec80081dd8a

**Binaries used during testing:**

You may want to check if these have the same hash as your generated artifacts. Because I'm not sure if the linked zephyr repo needs to be manually checked out to a specific version or not (mine is at https://github.com/zephyrproject-rtos/zephyr/commit/0a586db7b58269fb08248b081bdc3b43452da5f4)? I suppose west is managing the zephyr versions?

Firmware built from https://github.com/ReFil/zmk/commit/2f7db1adef5f4b01602379758ea48d940c6ab305 that contains the regression.
[2f7db1adef5f4b01602379758ea48d940c6ab305.zip](https://github.com/ReFil/zmk/files/12706613/2f7db1adef5f4b01602379758ea48d940c6ab305.zip)

Last tested stable version with the LED indicator patch applied, that doesn't have the disconnectivity issue (commit: https://github.com/ReFil/zmk/pull/8/commits/8af876c094d65f81410c790767818cd901fc31cf)
[8af876c094d65f81410c790767818cd901fc31cf.zip](https://github.com/ReFil/zmk/files/12706612/8af876c094d65f81410c790767818cd901fc31cf.zip)

**Comment by ReFil** [comment]
Ah i'm really sorry, I've chased out that bug but forgot to push. Please rebase and then remove the CONFIG_BT_PRIVACY=y line from your adv360_left_defconfig. also i think there's something up with the git commit history as it stillw ants to merge 80 commits

**Comment by cvcore** [comment]
Closed for #9 

The tests on my hardware has been positive. Thanks for the fix! Please review the newly created PR which also has a cleaner git log. @ReFil

**Pull request closed without merging**
