### PR TITLE
Latency improvements

### PR DESCRIPTION
**Pull request by aaronjensen**
See https://www.youtube.com/watch?v=jWL4nU-vtWs and https://twitter.com/zekjur/status/1572327757849174023

These commits were cherry-picked from upstream

### CODE REVIEW

**Comment by ReFil** [comment]
Hi, are these merged into zmk main yet?

**Comment by aaronjensen** [comment]
Yes, I cherry picked them from there.

**Comment by aaronjensen** [comment]
https://github.com/zmkfirmware/zmk/commit/d33b35513b4a01b365f6b82f6c0d63e22e56d849
https://github.com/zmkfirmware/zmk/commit/7443a917cb01484f2bb9fb9294c680eda343e24d

**Comment by ReFil** [comment]
In that case you might want to move to the V2.0 branch. You can update your config repo using the template provided . It not only has these fixes but dozens of others as it's a complete refactor from current zmk main. 

https://github.com/PolarityWorks/zmk-config-adv360/tree/Z3-update

**Comment by aaronjensen** [comment]
Right on, thanks!

**Pull request closed without merging**
